### ISSUE TITLE
Closing modal with livewire property causes error

### ISSUE THREAD

**Issue by BrendanBasson4** [PH7-Jack/livewire-ui#168]
I'm building a project with jetstream and for some reason when I close the model using its property I get this error:

> Uncaught (in promise) {isFromCancelledTransition: true}

and this error

> Uncaught (in promise) TypeError: l is not a function at VM15641 cdn.min.js:5:8569

### Modal:

`<x-modal.card title="Create Contact" blur wire:model.defer="create_contact_modal">`

### Property

`public $create_contact_modal;`

### Open modal
`$this->create_contact_modal = true;`

### Button that closes modal:

```
<div class="mt-2">
     <x-button primary label="Submit" wire:click="submit"/>
</div>
```

### Function that closes modal:

 ```
public function submit(){
        $this->validate();

        $this->contact->save();

        $this->resetErrorBag();

        unset($this->contact);

        $this->emit('getContacts');

        $this->create_contact_modal = false;
    }
```

Also this is running in a docker container via Laravel sail.

Am I doing something wrong?

**Comment by ph7jack** [comment]
@BrendanBasson4 
Please, inform your laravel version, livewire, alpine, and the browser

**Comment by BrendanBasson4** [comment]
- laravel/framework@8.75,
- livewire/livewire@2.5,
- alpinejs@3.7.1
- Chrome@97.0.4692.71

**Comment by Mutembeijoe** [comment]
I had this issue.
These errors would appear if i closed the modal with the close button or within the submit function like you described but not when using the x button on top of the modal. 
After closing the modal the page and datatable would become unresponsive, not able to click anything on that page, unless i refreshed the page. 
This errors appeared when i updated alpine from v3.0.6 to v3.8.1
I have tried other alpine versions and this problem seems to appear from v3.2.1
I am now using v 3.2.0

**Comment by Mutembeijoe** [comment]
Ensure you are not loading alpinejs multiple times. Probably via cdn and as a module.

**Comment by ph7jack** [comment]
@BrendanBasson4 
This issue is inactive for a long time, I'm closing it now.
If your error still persists, comment "RE-OPEN" and tag me
Thanks for using the WireUI
